FROM python:3.6.10-alpine
MAINTAINER Ji.Zhilong <zhilongji@gmail.com>

ADD . /usr/local/src/docker-make
WORKDIR /usr/local/src/docker-make

RUN pip install . &&\
    pip install -r test-requirements.txt &&\
    flake8 dmake && nosetests tests/
